#!/usr/bin/env python3
import os, sys, subprocess, signal, time, shutil
from datetime import datetime
from pathlib import Path

V = "2.0.0"
R = '\033[91m'; G = '\033[92m'; Y = '\033[93m'; C = '\033[96m'
W = '\033[97m'; D = '\033[2m'; L = '\033[1m'; X = '\033[0m'
BW = 56

def S(text, style=L): return f"{style}{text}{X}"

LOGO_LINES = [
    " _   _ ______ ______ ______ _____            __   __",
    "| \\ | |  ____|  ____|  ____|  __ \\     /\\    \\ \\ / /",
    "|  \\| | |__  | |__  | |__  | |__) |   /  \\    \\ V /",
    "| . ` |  __| |  __| |  __| |  _  /   / /\\ \\    > <",
    "| |\\  | |____| |    | |____| | \\ \\  / ____ \\  / . \\",
    "|_| \\_|______|_|    |______|_|  \\_\\/_/    \\_\\/_/ \\_\\",
]

LOGO = ""
for line in LOGO_LINES:
    LOGO += f"  {R}\u2551  {S(line)}{' '*(BW - len(line) - 4)}{R}\u2551{X}\n"

def logo():
    os.system('clear')
    print(f"  {R}\u2554{'\u2550'*BW}\u2557{X}")
    print(LOGO, end='')
    print(f"  {R}\u255a{'\u2550'*BW}\u255d{X}")
    sub = f"Dark Security Framework  v{V}  |  {S(f'{len(TOOLS)} tools',C)}  |  {S(f'{len(CHAINS)} chains',Y)}"
    print(f"  {D}\u2554{'\u2550'*BW}\u2557{X}")
    print(f"  {D}\u2551  {sub}{' '*(BW - len(sub) - 4)}{D}\u2551{X}")
    print(f"  {D}\u255a{'\u2550'*BW}\u255d{X}")
    print()

def box_start(title=None, sep=False):
    if title:
        print(f"  {R}\u2554{'\u2550'*BW}\u2557{X}")
        print(f"  {R}\u2551  {S(title)}{' '*(BW - len(title) - 4)}{R}\u2551{X}")
    else: print(f"  {R}\u2554{'\u2550'*BW}\u2557{X}")
    if sep: print(f"  {R}\u2560{'\u2550'*BW}\u2563{X}")

def box_end(): print(f"  {R}\u255a{'\u2550'*BW}\u255d{X}")
def box_line(text, style=W, pad=True):
    p = 2 if pad else 0; content = f"{style}{text}{X}" if style else text
    print(f"  {R}\u2551{' '*p}{content}{' '*(BW - len(text) - p)}{R}\u2551{X}")

def log(lvl, msg):
    sym = {"+":f"{G}\u2503 [+] \u2503{X}", "-":f"{R}\u2503 [-] \u2503{X}",
           "*":f"{C}\u2503 [*] \u2503{X}", "!":f"{Y}\u2503 [!] \u2503{X}",
           }
    print(f"  {D}\u2503{X} {sym.get(lvl,lvl).ljust(8)} {msg}")

REPORTS_DIR = Path.home() / ".hackingtool" / "reports"

# ── HTML Report Templates ──────────────────────────────────────────────
CSS = """*{margin:0;padding:0;box-sizing:border-box}
body{background:#0d1117;color:#c9d1d9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',monospace;padding:30px;max-width:960px;margin:auto}
h1{color:#e94560;border-bottom:2px solid #30363d;padding-bottom:10px;margin-bottom:25px}
h2{color:#58a6ff;margin:25px 0 15px}
.badge{display:inline-block;padding:3px 12px;border-radius:4px;font-size:13px;font-weight:600}
.badge-green{background:#1f6f2b;color:#fff}
.badge-red{background:#8b1a1a;color:#fff}
.badge-yellow{background:#9e6a03;color:#fff}
.muted{color:#8b949e;font-size:13px}
pre{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:16px;overflow-x:auto;white-space:pre-wrap;font-size:13px;line-height:1.5}
.grid{display:grid;grid-template-columns:110px 1fr;gap:8px;margin:20px 0}
.grid dt{color:#8b949e}
.grid dd{margin:0}
.flex{display:flex;gap:16px;margin:20px 0;flex-wrap:wrap}
.flex>div{text-align:center;padding:18px 28px;border-radius:6px;background:#161b22;border:1px solid #30363d;flex:1;min-width:100px}
.flex .num{font-size:30px;font-weight:700}
table{width:100%;border-collapse:collapse;margin:20px 0}
th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #30363d}
th{color:#8b949e;font-weight:600;font-size:13px}
.tool-row td{font-size:14px}
a{color:#58a6ff;text-decoration:none}
a:hover{text-decoration:underline}
.section{border:1px solid #30363d;border-radius:6px;padding:16px;margin:16px 0}
"""

def _gen_html(title, body_parts):
    parts = "\n".join(body_parts)
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title} - Neferax</title><style>{CSS}</style></head>
<body>
<h1>\u26a1 Neferax &mdash; {title}</h1>
{parts}
<hr><p class="muted">Generated by Neferax v{V} | mastergeeky1-cloud/neferax</p>
</body></html>"""

def _make_report_path(name, ext="html"):
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe = name.replace("/","_").replace(" ","_").replace("|","_")[:40]
    return REPORTS_DIR / f"{ts}_{safe}.{ext}"

def _timefmt(ms):
    if ms < 1000: return f"{ms:.0f}ms"
    return f"{ms/1000:.1f}s"

def write_tool_report(tool_name, target, cmd, stdout, stderr, exit_code, duration_ms, methods=None):
    fpath = _make_report_path(tool_name)
    status = "pass" if exit_code == 0 else ("timeout" if exit_code == -1 else "fail")
    badge = f'<span class="badge badge-{"green" if exit_code==0 else ("yellow" if exit_code==-1 else "red")}">{"PASS" if exit_code==0 else ("TIMEOUT" if exit_code==-1 else "FAIL")}</span>'
    methods_str = ", ".join(methods) if methods else "\u2014"
    output = (stdout + stderr).strip() or "(no output)"

    body = [
        f'<div class="grid"><dt>Tool</dt><dd><strong>{tool_name}</strong></dd>',
        f'<dt>Target</dt><dd>{target}</dd>',
        f'<dt>Time</dt><dd class="muted">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</dd>',
        f'<dt>Duration</dt><dd class="muted">{_timefmt(duration_ms)}</dd>',
        f'<dt>Methods</dt><dd class="muted">{methods_str}</dd>',
        f'<dt>Status</dt><dd>{badge}</dd></div>',
        '<h2>Command</h2>',
        f'<pre>$ {cmd}</pre>',
        '<h2>Output</h2>',
        f'<pre>{output}</pre>',
    ]
    fpath.write_text(_gen_html(f"Tool: {tool_name}", body))
    return fpath

def write_chain_report(chain_name, target, results):
    fpath = _make_report_path(f"chain_{chain_name}")
    total = len(results)
    passed = sum(1 for r in results if r["exit_code"] == 0)
    failed = sum(1 for r in results if r["exit_code"] not in (0, -1))
    timedout = sum(1 for r in results if r["exit_code"] == -1)
    total_ms = sum(r["duration_ms"] for r in results)

    rows = ""
    for r in results:
        cls = "green" if r["exit_code"] == 0 else ("yellow" if r["exit_code"] == -1 else "red")
        lbl = "PASS" if r["exit_code"] == 0 else ("TIMEOUT" if r["exit_code"] == -1 else "FAIL")
        rp = r.get("report_path", "")
        link = f'<a href="{rp.name}">\ud83d\udcc4 view</a>' if rp else "\u2014"
        rows += f'<tr class="tool-row"><td>{r["tool"]}</td>'
        rows += f'<td>{r["target"]}</td>'
        rows += f'<td>{_timefmt(r["duration_ms"])}</td>'
        rows += f'<td><span class="badge badge-{cls}">{lbl}</span></td>'
        rows += f'<td>{link}</td></tr>'

    body = [
        f'<div class="grid"><dt>Chain</dt><dd><strong>{chain_name.upper()}</strong></dd>',
        f'<dt>Target</dt><dd>{target}</dd>',
        f'<dt>Time</dt><dd class="muted">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</dd>',
        f'<dt>Total Duration</dt><dd class="muted">{_timefmt(total_ms)}</dd></div>',
        '<div class="flex">',
        f'<div><div class="num">{total}</div><div class="muted">Tools</div></div>',
        f'<div><div class="num" style="color:#3fb950">{passed}</div><div class="muted">Passed</div></div>',
        f'<div><div class="num" style="color:#f85149">{failed}</div><div class="muted">Failed</div></div>',
        f'<div><div class="num" style="color:#d29922">{timedout}</div><div class="muted">Timeout</div></div></div>',
        '<table><tr><th>Tool</th><th>Target</th><th>Duration</th><th>Status</th><th>Report</th></tr>',
        rows, '</table>',
        '<h2>Execution Timeline</h2>',
        '<pre>' + '\n'.join(f'[{_timefmt(r["duration_ms"]):>6}] {r["tool"]:25} {"PASS" if r["exit_code"]==0 else "FAIL"} {r["target"]}' for r in results) + '</pre>',
    ]
    fpath.write_text(_gen_html(f"Chain: {chain_name.upper()}", body))
    return fpath

def write_report_index():
    fpath = REPORTS_DIR / "index.html"
    reports = sorted(REPORTS_DIR.glob("*.html"), key=lambda p: p.stat().st_mtime, reverse=True)
    rows = ""
    for r in reports[:100]:
        if r.name == "index.html": continue
        rows += f'<tr><td><a href="{r.name}">{r.name}</a></td><td class="muted">{r.stat().st_size:,}B</td></tr>'
    body = [
        f'<p class="muted">{len(reports)-1} reports</p>',
        '<table><tr><th>Report</th><th>Size</th></tr>',
        rows, '</table>',
    ]
    if not rows:
        body.insert(0, '<p>No reports yet. Run a tool to generate reports.</p>')
    fpath.write_text(_gen_html("Report Index", body))
    return fpath

# ── Permission & Installation Checking ─────────────────────────────────
SUDO_REQUIRED = {
    "aircrack","airodump","aireplay","airmon","arp-scan","bettercap","bully",
    "chntpw","cowpatty","ettercap","evil-winrm","hashcat","hydra","john",
    "kismet","macchanger","masscan","mdk4","medusa","nbtscan","ncrack",
    "netdiscover","nmap","onesixtyone","reaver","responder","samdump2",
    "set","snmpcheck","tcpdump","tshark","wifite","reaver","pixiewps",
}

def check_tool(tool_name):
    """Returns (installed, needs_sudo, binary_name)"""
    if tool_name not in TOOLS:
        return False, False, None
    cmd = TOOLS[tool_name]["cmd"].split()[0]
    cmd = cmd.split("|")[0].strip()
    bin_found = shutil.which(cmd) is not None
    needs_sudo = tool_name in SUDO_REQUIRED
    return bin_found, needs_sudo, cmd

# ── Tool Execution ─────────────────────────────────────────────────────
def run(tool_name, target="", desc=None):
    if tool_name not in TOOLS:
        log("-", f"Unknown tool: {tool_name}")
        return -1, 0

    info = TOOLS[tool_name]
    raw_cmd = info["cmd"]
    cmd = raw_cmd.replace("<target>",target).replace("<domain>",target).replace("<url>",target)

    installed, needs_sudo, binary = check_tool(tool_name)

    if not installed and binary:
        log("!", f"'{binary}' not installed. Install: sudo apt install {binary}")
        return -1, 0

    if needs_sudo and os.geteuid() != 0:
        log("*", f"Requires root — prepending sudo")
        cmd = f"sudo {cmd}"

    print(f"  {R}\u2554{'\u2550'*BW}\u2557{X}")
    header = desc or f"{tool_name} on {target or '(no target)'}"
    print(f"  {R}\u2551  {S(header)}{' '*(BW - len(header) - 4)}{R}\u2551{X}")
    print(f"  {R}\u2551  {D}{cmd}{X}{' '*(BW - len(cmd) - 4)}{R}\u2551{X}")
    print(f"  {R}\u255a{'\u2550'*BW}\u255d{X}")

    start = time.time()
    stdout_buf = []
    stderr_buf = []
    exit_code = 0
    try:
        p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE, universal_newlines=True, bufsize=1)
        for line in p.stdout:
            print(f"  {W}  {line}", end='')
            stdout_buf.append(line)
        for line in p.stderr:
            stderr_buf.append(line)
        p.wait()
        exit_code = p.returncode
    except KeyboardInterrupt:
        log("!", "Interrupted by user")
        exit_code = -1
    except Exception as e:
        log("-", str(e))
        exit_code = -1

    duration_ms = (time.time() - start) * 1000

    if exit_code == 0:
        log("+", f"Done ({_timefmt(duration_ms)})")
    else:
        log("!" if exit_code != -1 else "*", f"Exit: {exit_code} ({_timefmt(duration_ms)})")

    # Generate HTML report
    stdout_str = "".join(stdout_buf)
    stderr_str = "".join(stderr_buf)
    rpath = write_tool_report(tool_name, target or "(none)", cmd, stdout_str, stderr_str,
                              exit_code, duration_ms, info.get("methods"))
    log("*", f"Report: {rpath}")
    write_report_index()

    return exit_code, duration_ms, str(rpath)

# ── Tool Database ──────────────────────────────────────────────────────
TOOLS = {}
METHODS_MAP = {}

def tool(name, cmd, cat="misc", desc="", methods=None, sudo=False):
    TOOLS[name] = {"cmd": cmd, "cat": cat, "desc": desc, "methods": methods or []}
    if sudo: SUDO_REQUIRED.add(name)

# ── RECON ──
tool("nmap","nmap <target>","recon","Network discovery & security auditing",
     methods=["port_scan","service_detection","os_detection","script_scan","version_detection"])
tool("masscan","masscan --rate=1000 -p1-65535 <target>","recon","Fast internet port scanner",
     methods=["port_scan","mass_scan"])
tool("netdiscover","netdiscover -r <target>","recon","Passive/active ARP scanner",
     methods=["arp_discovery","network_discovery"])
tool("arp-scan","arp-scan --localnet","recon","ARP scan local network",
     methods=["arp_discovery","host_discovery"])
tool("theharvester","theHarvester -d <domain> -b all","recon","Email, subdomain & name OSINT",
     methods=["osint","email_harvest","subdomain_enum","dns_recon"])
tool("dnsrecon","dnsrecon -d <target> -t std","recon","DNS enumeration tool",
     methods=["dns_recon","zone_transfer","dns_brute"])
tool("dnsenum","dnsenum <target>","recon","DNS enumeration utility",
     methods=["dns_recon","zone_transfer"])
tool("fierce","fierce --domain <domain>","recon","DNS reconnaissance",
     methods=["dns_recon","subdomain_enum"])
tool("amass","amass enum -d <domain>","recon","Attack surface mapping",
     methods=["subdomain_enum","osint","dns_recon","attack_surface"])
tool("dmitry","dmitry <target>","recon","Deepmagic info gathering",
     methods=["osint","whois","port_scan"])
tool("enum4linux","enum4linux -a <target>","recon","Windows/Samba enumeration",
     methods=["smb_enum","os_enum","user_enum","share_enum"])
tool("netexec","netexec smb <target>","recon","Network execution suite",
     methods=["smb_enum","winrm_enum","auth_test"])
tool("smbmap","smbmap -H <target>","recon","SMB share enumeration",
     methods=["smb_enum","share_enum"])
tool("nbtscan","nbtscan <target>","recon","NetBIOS name scanner",
     methods=["netbios_enum","name_discovery"])
tool("onesixtyone","onesixtyone <target>","recon","SNMP scanner",
     methods=["snmp_scan","community_enum"])
tool("snmpcheck","snmpcheck -t <target>","recon","SNMP enumeration",
     methods=["snmp_enum","info_disclosure"])
tool("hping3","hping3 -c 4 <target>","recon","Packet crafting & analysis",
     methods=["packet_craft","firewall_test","os_fingerprint"])
tool("fping","fping -asg <target>","recon","Ping sweep tool",
     methods=["host_discovery","ping_sweep"])
tool("ike-scan","ike-scan <target>","recon","IKE VPN scanning",
     methods=["vpn_scan","ike_enum","trans_discovery"])
tool("dnschef","dnschef","recon","DNS proxy/spoofer",
     methods=["dns_spoof","dns_proxy","dns_recon"])
tool("recon-ng","recon-ng","recon","Web reconnaissance framework",
     methods=["osint","recon","module_based"])
tool("spiderfoot","spiderfoot -s <target>","recon","OSINT automation",
     methods=["osint","threat_intel","footprinting"])
tool("whois","whois <target>","recon","Domain registration lookup",
     methods=["whois","domain_intel"])

# ── WEB ──
tool("nikto","nikto -h <target>","web","Web server scanner",
     methods=["web_scan","vuln_detection","cgi_scan","misconfig"])
tool("whatweb","whatweb -v <target>","web","Web technology identifier",
     methods=["fingerprint","tech_detection"])
tool("wpscan","wpscan --url <target> --enumerate vp,vt,u","web","WordPress security scanner",
     methods=["wp_scan","wp_vuln","wp_enum","plugin_scan","theme_scan","user_enum"])
tool("skipfish","skipfish -o /tmp/skipfish <target>","web","Web app security scanner",
     methods=["web_crawl","vuln_detection","fuzz"])
tool("wafw00f","wafw00f <target>","web","WAF detection fingerprinting",
     methods=["waf_detect","fingerprint"])
tool("gobuster","gobuster dir -u <target> -w /usr/share/wordlists/dirb/common.txt","web","Directory/file brute-forcer",
     methods=["dir_brute","dns_enum","vhost_scan"])
tool("dirb","dirb <target>","web","Web content scanner",
     methods=["dir_brute","web_crawl"])
tool("ffuf","ffuf -w /usr/share/wordlists/dirb/common.txt -u <target>/FUZZ","web","Fast web fuzzer",
     methods=["fuzz","dir_brute","parameter_fuzz","vhost_fuzz"])
tool("wfuzz","wfuzz -w /usr/share/wordlists/wfuzz/general/common.txt <target>","web","Web fuzzer",
     methods=["fuzz","dir_brute","parameter_fuzz"])
tool("sqlmap","sqlmap -u <target> --batch","web","SQL injection automation",
     methods=["sqli","blind_sqli","time_sqli","error_sqli","union_sqli","db_fingerprint"])
tool("commix","commix --url=<target>","web","Command injection exploiter",
     methods=["cmdi","blind_cmdi","time_cmdi"])
tool("lbd","lbd <domain>","web","Load balancing detector",
     methods=["lb_detect","reverse_proxy_detect"])

# ── EXPLOIT ──
tool("searchsploit","searchsploit <query>","exploit","Exploit-DB search tool",
     methods=["exploit_search","vuln_research"])
tool("metasploit","msfconsole -q","exploit","Metasploit framework console",
     methods=["exploit","payload","post_exploit","auxiliary"])
tool("set","setoolkit","exploit","Social Engineer Toolkit",
     methods=["phishing","cred_harvest","payload_gen","web_attack"])
tool("hydra","hydra -l root -P /usr/share/wordlists/rockyou.txt.gz <target> <service>","exploit","Online password brute-forcer",
     methods=["brute_force","auth_bypass","online_attack"], sudo=True)
tool("ncrack","ncrack -p 22 -U /usr/share/wordlists/rockyou.txt.gz <target>","exploit","Network authentication cracker",
     methods=["brute_force","auth_bypass","online_attack"], sudo=True)
tool("medusa","medusa -h <target> -u root -P /usr/share/wordlists/rockyou.txt.gz -M ssh","exploit","Parallel brute-forcer",
     methods=["brute_force","auth_bypass","online_attack"], sudo=True)
tool("weevely","weevely <url> <password>","exploit","Web shell manager",
     methods=["webshell","persistence","remote_access"])

# ── PASSWORD ──
tool("hashcat","hashcat -m 0 -a 0 <hashfile> /usr/share/wordlists/rockyou.txt.gz","password","GPU-accelerated hash cracker",
     methods=["hash_crack","gpu_crack","rule_attack","mask_attack","dictionary_attack"])
tool("john","john --wordlist=/usr/share/wordlists/rockyou.txt.gz <hashfile>","password","John the Ripper",
     methods=["hash_crack","dictionary_attack","incremental","rule_attack"])
tool("crunch","crunch 8 12 abcdefghijklmnopqrstuvwxyz","password","Wordlist generator",
     methods=["wordlist_gen","mask_gen","custom_gen"])
tool("cewl","cewl <url> -w wordlist.txt","password","Custom wordlist generator",
     methods=["wordlist_gen","spider","custom_gen"])
tool("hashid","hashid <hashfile>","password","Hash type identifier",
     methods=["hash_id","hash_detect"])
tool("gpp-decrypt","gpp-decrypt <hash>","password","Decrypt GPP passwords",
     methods=["gpp_decrypt","ad_decrypt"])
tool("rsmangler","rsmangler --file <wordlist>","password","Wordlist mutation tool",
     methods=["wordlist_mutate","rule_gen"])
tool("pipal","pipal <wordlist>","password","Password analyzer",
     methods=["password_analyze","stats","pattern_detect"])

# ── WIRELESS ──
tool("aircrack","aircrack-ng <capture.cap>","wireless","WEP/WPA/WPA2 cracker",
     methods=["wep_crack","wpa_crack","pcap_analyze"], sudo=True)
tool("airodump","airodump-ng <interface>","wireless","Packet capture",
     methods=["packet_capture","network_discovery","channel_hop"], sudo=True)
tool("aireplay","aireplay-ng -0 5 -a <bssid> <interface>","wireless","Packet injection",
     methods=["deauth","arp_replay","packet_inject"], sudo=True)
tool("airmon","airmon-ng start <interface>","wireless","Monitor mode manager",
     methods=["monitor_mode","interface_mgmt"], sudo=True)
tool("wifite","wifite","wireless","Automated wireless auditor",
     methods=["wpa_audit","wep_audit","wps_audit","auto_crack"], sudo=True)
tool("reaver","reaver -i <interface> -b <bssid> -vv","wireless","WPS PIN brute-force",
     methods=["wps_brute","pin_attack"], sudo=True)
tool("macchanger","macchanger -r <interface>","wireless","MAC address changer",
     methods=["mac_spoof","anon"], sudo=True)
tool("kismet","kismet","wireless","Wireless detector/sniffer",
     methods=["packet_capture","network_discovery","sniff"], sudo=True)
tool("mdk4","mdk4 <interface> d","wireless","Wireless DoS tool",
     methods=["deauth","beacon_flood","dos"], sudo=True)
tool("bettercap","bettercap -eval 'net.probe on; net.show'","wireless","Network attack framework",
     methods=["arp_spoof","dns_spoof","http_sniff","cred_capture"], sudo=True)
tool("bully","bully <interface> -b <bssid>","wireless","WPS brute-force",
     methods=["wps_brute","pin_attack"], sudo=True)
tool("pixiewps","pixiewps --e-hash1=<hash>","wireless","WPS offline brute-force",
     methods=["wps_crack","offline_attack","pixie_dust"])

# ── AD/WIN ──
tool("responder","responder -I <interface> -wrf","ad","LLMNR/NBT-NS/mDNS poisoner",
     methods=["llmnr_poison","ntlm_capture","name_spoof"], sudo=True)
tool("evil-winrm","evil-winrm -i <target> -u admin -p password","ad","WinRM shell",
     methods=["winrm_access","remote_shell","persistence"])
tool("samdump2","samdump2 <system> <sam>","ad","Extract Windows password hashes",
     methods=["hash_dump","cred_extract","sam_dump"], sudo=True)
tool("chntpw","chntpw <SAM>","ad","Windows password reset",
     methods=["password_reset","local_auth_bypass"], sudo=True)

# ── TUNNEL ──
tool("proxychains","proxychains <command>","tunnel","Force apps through proxy",
     methods=["proxy","tunnel","anon"])
tool("socat","socat TCP-LISTEN:8080,fork TCP:<target>:80","tunnel","Multipurpose relay",
     methods=["port_forward","relay","tunnel","reverse_shell"])
tool("ncat","ncat -lvp 8080","tunnel","Netcat with SSL",
     methods=["reverse_shell","bind_shell","port_listen","file_xfer"])
tool("iodine","iodine -d <server>","tunnel","DNS tunnel",
     methods=["dns_tunnel","doh_tunnel"])
tool("redsocks","redsocks","tunnel","Transparent redirector",
     methods=["proxy","redirect","transparent_proxy"])

# ── MITM ──
tool("mitmproxy","mitmproxy","mitm","Intercepting proxy",
     methods=["http_intercept","ssl_intercept","traffic_mod","replay"])
tool("ettercap","ettercap -T -M arp:remote /<gateway>// /<target>//","mitm","ARP poisoning suite",
     methods=["arp_poison","dns_spoof","traffic_sniff","ssl_strip"], sudo=True)
tool("sslstrip","sslstrip","mitm","SSL stripping",
     methods=["ssl_strip","https_downgrade"])
tool("sslscan","sslscan <target>","mitm","SSL/TLS scanner",
     methods=["ssl_scan","tls_test","cipher_check","cert_check"])
tool("sslyze","sslyze <target>","mitm","SSL/TLS config analyzer",
     methods=["ssl_scan","tls_audit","cipher_enum","cert_analyze"])

# ── TRAFFIC ──
tool("tcpdump","tcpdump -i any -n","traffic","Packet analyzer",
     methods=["packet_capture","traffic_analyze","sniff"], sudo=True)
tool("tshark","tshark -i any","traffic","Wireshark CLI tool",
     methods=["packet_capture","protocol_analyze","traffic_decrypt"], sudo=True)
tool("ngrep","ngrep -d any","traffic","Network grep",
     methods=["traffic_sniff","pattern_match"])

# ── REVERSE ──
tool("radare2","r2 <binary>","reverse","Reverse engineering framework",
     methods=["binary_analysis","disasm","debug","patch","decompile"])
tool("gdb","gdb <binary>","reverse","GNU debugger",
     methods=["debug","disasm","memory_analyze","crash_analyze"])
tool("nasm","nasm -f elf64 <file>.asm","reverse","Netwide assembler",
     methods=["assembly","shellcode"])
tool("binwalk","binwalk <file>","reverse","Firmware analysis",
     methods=["firmware_analyze","file_extract","entropy","signature"])
tool("foremost","foremost -i <file>","reverse","File carving",
     methods=["file_carve","data_recovery","forensics"])
tool("exiv2","exiv2 <file>","reverse","Image metadata tool",
     methods=["metadata","exif","forensics"])

# ── MISC ──
tool("arping","arping <target>","misc","ARP ping",
     methods=["host_discovery","arp_probe"])
tool("windows-binaries","windows-binaries","misc","Windows binary collection",
     methods=["binary_collection","win_bins"])
tool("webshells","webshells","misc","Web shell collection",
     methods=["webshell","persistence"])
tool("laudanum","laudanum","misc","Web shell injection kit",
     methods=["webshell","file_upload","reverse_shell"])

# ── Categories ─────────────────────────────────────────────────────────
CATS = [
    ("RECON",    [n for n,v in TOOLS.items() if v["cat"]=="recon"]),
    ("WEB",      [n for n,v in TOOLS.items() if v["cat"]=="web"]),
    ("EXPLOIT",  [n for n,v in TOOLS.items() if v["cat"]=="exploit"]),
    ("PASSWORD", [n for n,v in TOOLS.items() if v["cat"]=="password"]),
    ("WIRELESS", [n for n,v in TOOLS.items() if v["cat"]=="wireless"]),
    ("AD/WIN",   [n for n,v in TOOLS.items() if v["cat"]=="ad"]),
    ("TUNNEL",   [n for n,v in TOOLS.items() if v["cat"]=="tunnel"]),
    ("MITM",     [n for n,v in TOOLS.items() if v["cat"]=="mitm"]),
    ("TRAFFIC",  [n for n,v in TOOLS.items() if v["cat"]=="traffic"]),
    ("REVERSE",  [n for n,v in TOOLS.items() if v["cat"]=="reverse"]),
    ("MISC",     [n for n,v in TOOLS.items() if v["cat"]=="misc"]),
]

CHAINS = {
    "scan":     ("Quick vulnerability scan",                 ["nmap", "gobuster", "nikto"]),
    "recon":    ("Full reconnaissance",                      ["theharvester","dnsrecon","nmap","masscan","enum4linux","netexec"]),
    "web":      ("Web application attack",                   ["whatweb","nikto","wpscan","dirb","gobuster","ffuf","sqlmap"]),
    "exploit":  ("Exploitation chain",                       ["searchsploit","nmap","hydra"]),
    "brute":    ("Brute force (ssh ftp http mysql smb)",     []),
    "osint":    ("OSINT gathering",                          ["theharvester","dnsrecon","dnsenum","fierce","amass","cewl"]),
    "ad":       ("Active Directory",                         ["enum4linux","netexec","smbmap","responder"]),
    "wireless": ("Wireless attacks",                         ["airmon","airodump","aireplay","aircrack","wifite","reaver"]),
    "password": ("Password cracking",                        ["hashid","hashcat","john","crunch","cewl"]),
    "sql":      ("SQL injection",                            ["sqlmap"]),
    "full":     ("Full attack chain (recon+web+exploit+brute)",[]),
}

# ── Chain Runner ───────────────────────────────────────────────────────
def run_chain(name, target):
    chain = CHAINS.get(name)
    if not chain: return
    logo()
    box_start(f"{name.upper()}  \u2502 {chain[0]}  \u2502 {S(target,G)}")
    start = time.time()
    results = []

    for tool_name in chain[1]:
        if tool_name not in TOOLS: continue
        cmd = TOOLS[tool_name]["cmd"].replace("<target>",target).replace("<domain>",target).replace("<url>",target)
        ec, dur, rp = run(tool_name, target, f"Running {tool_name} on {target}")
        print()
        results.append({"tool": tool_name, "target": target, "exit_code": ec,
                        "duration_ms": dur, "report_path": rp})

    if name == "brute":
        for svc in ["ssh","ftp","http-post-form","mysql","smb"]:
            c = f"hydra -l root -P /usr/share/wordlists/rockyou.txt.gz {target} {svc}"
            ec, dur, rp = run("hydra", target, f"Brute forcing {svc} on {target}")
            print()
            results.append({"tool": f"hydra-{svc}", "target": target, "exit_code": ec,
                            "duration_ms": dur, "report_path": rp})

    if name == "full":
        for sub in ["recon","web","exploit","brute"]:
            run_chain(sub, target)

    elapsed = (time.time() - start) * 1000
    box_end()
    log("+", f"Chain '{name}' completed in {_timefmt(elapsed)}")

    # Generate final chain report
    if results:
        rpath = write_chain_report(name, target, results)
        write_report_index()
        log("*", f"Chain report: {rpath}")
    box_end()

# ── Display Functions ──────────────────────────────────────────────────
def do_list():
    logo()
    box_start("TOOLS DATABASE", sep=True)
    for cat_name, tools in CATS:
        if not tools: continue
        box_line(f" {S(cat_name)}", R)
        for tn in tools:
            m = ", ".join(TOOLS[tn].get("methods", [])[:3])
            box_line(f"  {tn:22}{D}{m[:30]}{X}")
        box_line(f"{D}{'─'*BW}{X}", pad=False)
    box_start("ATTACK CHAINS", sep=True)
    for n, (d, _) in CHAINS.items():
        box_line(f"  {S(n + ':')}  {d}")
    box_end()

def do_help():
    logo()
    box_start("NEFERAX \u2014 Dark Security Framework", sep=True)
    box_line(f"{D}Usage:  {C}nefereax <command> [options] <target>{X}", D)
    box_line("")
    box_line(f"{S('ATTACK CHAINS:')}", R)
    for n, (d, _) in CHAINS.items():
        box_line(f"  {S(n):14}{d}")
    box_line("")
    box_line(f"{S('COMMANDS:')}", R)
    for c_, d_ in [("list","List all tools with methods"),("search <q>","Search tools"),
                   ("info <t>","Tool details"),("reports","Open report index"),
                   ("menu","Interactive TUI"),("version","Show version")]:
        box_line(f"  {S(c_):14}{d_}")
    box_line("")
    box_line(f"{S('FILTER:')}", R)
    box_line(f"  {S('--method <m>')}  Filter by attack method (port_scan, sqli, osint, ...)")
    box_line("")
    box_line(f"{S('EXAMPLES:')}", R)
    for c_, d_ in [("nefereax scan 10.10.10.1","Quick scan + HTML report"),
                   ("nefereax full 192.168.1.0/24","Full chain + aggregated report"),
                   ("nefereax search --method sqli","Search by attack method"),
                   ("nefereax reports","Open HTML report index")]:
        box_line(f"  {D}{c_:35}{X}  {d_}")
    box_end()

def do_version():
    logo()
    box_start(f"Nefereax v{V}  |  Dark Security Framework")
    box_line(f"  {D}{len(TOOLS)} tools  |  {len(CHAINS)} attack chains{X}")
    box_line(f"  {D}Reports: {REPORTS_DIR}{X}")
    box_end()

def do_search(query, method=None):
    found = [(n, v) for n, v in TOOLS.items()
             if query in n.lower() or query in v["desc"].lower() or query in v["cmd"].lower() or query in v["cat"]]
    if method:
        found = [(n, v) for n, v in found if method.lower() in [m.lower() for m in v.get("methods", [])]]
    logo()
    box_start(f"SEARCH  {D}for '{query}'{f'  method:{method}' if method else ''}{X}")
    if found:
        for n, v in sorted(found):
            m = ", ".join(v.get("methods", [])[:3])
            box_line(f"  {S(n):25}{D}{m[:30]}{X}")
        box_line(f"  {D}({len(found)} results){X}")
    else:
        box_line(f"  {Y}No matches{X}")
    box_end()

def do_info(name):
    logo()
    if name in TOOLS:
        v = TOOLS[name]
        box_start(f"TOOL: {name}")
        box_line(f"  {D}Category: {v['cat']}{X}")
        box_line(f"  {D}Usage:     {C}{v['cmd']}{X}")
        box_line(f"  {D}About:     {v['desc']}{X}")
        methods = v.get("methods", [])
        if methods:
            box_line(f"  {D}Methods:   {', '.join(methods)}{X}")
        inst, sudo, binary = check_tool(name)
        box_line(f"  {D}Installed: {'yes' if inst else 'no'}{X}")
        if sudo: box_line(f"  {D}Requires:  root privileges{X}")
    elif name in CHAINS:
        box_start(f"CHAIN: {name}")
        box_line(f"  {CHAINS[name][0]}")
        box_line(f"  {D}nefereax {name} <target>{X}")
    else:
        box_start(f"Unknown: {name}")
    box_end()

def do_reports():
    rp = write_report_index()
    rdir = REPORTS_DIR
    count = len(list(rdir.glob("*.html"))) - 1
    logo()
    box_start("REPORTS")
    box_line(f"  {D}Directory: {rdir}{X}")
    box_line(f"  {D}Reports:   {count}{X}")
    box_line(f"  {D}Index:     {rp}{X}")
    box_line(f"  {D}Open in browser: file://{rp}{X}")
    box_end()
    log("*", f"Open: file://{rp}")

def do_unknown(cmd):
    logo()
    box_start(f"{Y}Unknown: {cmd}{X}")
    box_line(f"  {D}Run 'nefereax --help' for usage{X}")
    box_end()

# ── Main ───────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) < 2 or sys.argv[1] in ("-h","--help","help"):
        do_help(); return 0

    cmd = sys.argv[1]
    if cmd == "version": do_version(); return 0
    if cmd == "menu": os.execv("/usr/bin/hackingtool", ["hackingtool"])
    if cmd == "list": do_list(); return 0
    if cmd == "reports": do_reports(); return 0

    if cmd == "search":
        args = [a for a in sys.argv[2:]]
        method = None
        query = ""
        for i, a in enumerate(args):
            if a == "--method" and i+1 < len(args):
                method = args[i+1]
            elif not a.startswith("--"):
                query = a
        if not query:
            logo(); log("-", "Usage: nefereax search [--method <m>] <query>"); return 1
        do_search(query.lower(), method); return 0

    if cmd == "info":
        if len(sys.argv) < 3:
            logo(); log("-", "Usage: nefereax info <tool>"); return 1
        do_info(" ".join(sys.argv[2:]).lower()); return 0

    if cmd in CHAINS:
        if len(sys.argv) < 3:
            logo(); log("-", f"Usage: nefereax {cmd} <target>"); return 1
        target = " ".join(sys.argv[2:])
        signal.signal(signal.SIGINT, lambda s, f: sys.exit(0))
        run_chain(cmd, target); return 0

    if cmd in TOOLS:
        if len(sys.argv) < 3:
            logo()
            box_start("Usage")
            box_line(f"  {TOOLS[cmd]['cmd']}")
            box_end()
            return 1
        target = " ".join(sys.argv[2:])
        logo()
        run(cmd, target, f"{cmd} on {target}")
        return 0

    do_unknown(cmd)
    return 1

if __name__ == "__main__":
    sys.exit(main())
