from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path.home() / ".hackingtool" / "reports"

def ensure_dir():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

CSS = """
body{background:#0d1117;color:#c9d1d9;font-family:monospace;margin:30px}
h1{color:#e94560;border-bottom:2px solid #30363d;padding-bottom:10px}
h2{color:#58a6ff;margin-top:30px}
.status{display:inline-block;padding:3px 12px;border-radius:4px;font-weight:bold}
.pass{background:#1f6f2b;color:#fff}
.fail{background:#8b1a1a;color:#fff}
.timeout{background:#9e6a03;color:#fff}
.info{color:#8b949e;font-size:13px}
pre{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:16px;overflow-x:auto;white-space:pre-wrap}
.meta{display:grid;grid-template-columns:120px 1fr;gap:8px;margin:20px 0}
.meta dt{color:#8b949e}
.meta dd{margin:0}
.summary{display:flex;gap:20px;margin:20px 0}
.summary div{text-align:center;padding:15px 25px;border-radius:6px;background:#161b22;border:1px solid #30363d}
.summary .num{font-size:28px;font-weight:bold}
table{width:100%;border-collapse:collapse;margin:20px 0}
th,td{padding:10px;text-align:left;border-bottom:1px solid #30363d}
th{color:#8b949e}
.tool-row{color:#c9d1d9}
a{color:#58a6ff;text-decoration:none}
a:hover{text-decoration:underline}
.chain-header{background:#1c2333;border:1px solid #30363d;border-radius:6px;padding:15px;margin:15px 0}
"""

def single_report(title, target, cmd, output, exit_code, duration_ms, methods=None):
    ensure_dir()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe = title.replace("/","_").replace(" ","_")
    fname = f"report_{ts}_{safe}.html"
    fpath = REPORTS_DIR / fname

    status = "pass" if exit_code == 0 else ("timeout" if exit_code == -1 else "fail")
    label = "PASS" if exit_code == 0 else ("TIMEOUT" if exit_code == -1 else "FAIL")
    methods_str = ", ".join(methods) if methods else "—"

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title} - Neferax Report</title>
<style>{CSS}</style></head><body>
<h1>⚡ Neferax — Tool Report</h1>
<div class="meta">
<dt>Tool</dt><dd><strong>{title}</strong></dd>
<dt>Target</dt><dd>{target}</dd>
<dt>Time</dt><dd class="info">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</dd>
<dt>Duration</dt><dd class="info">{duration_ms:.0f}ms</dd>
<dt>Methods</dt><dd class="info">{methods_str}</dd>
<dt>Status</dt><dd><span class="status {status}">{label}</span></dd>
</div>
<h2>Command</h2>
<pre>$ {cmd}</pre>
<h2>Output</h2>
<pre>{output}</pre>
<hr><p class="info">Generated by Neferax v2.0.0 — mastergeeky1-cloud/neferax</p>
</body></html>"""

    fpath.write_text(html)
    return fpath

def chain_report(chain_name, target, results):
    ensure_dir()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    fname = f"chain_{ts}_{chain_name}.html"
    fpath = REPORTS_DIR / fname

    total = len(results)
    passed = sum(1 for r in results if r["exit_code"] == 0)
    failed = sum(1 for r in results if r["exit_code"] not in (0, -1))
    timedout = sum(1 for r in results if r["exit_code"] == -1)
    total_ms = sum(r["duration_ms"] for r in results)

    rows = ""
    for r in results:
        cls = "pass" if r["exit_code"] == 0 else ("timeout" if r["exit_code"] == -1 else "fail")
        lbl = "PASS" if r["exit_code"] == 0 else ("TIMEOUT" if r["exit_code"] == -1 else "FAIL")
        report_link = r.get("report_path", "")
        link = f'<a href="{report_link}">view</a>' if report_link else "—"
        rows += f'<tr class="tool-row"><td>{r["tool"]}</td><td>{r["duration_ms"]:.0f}ms</td>'
        rows += f'<td><span class="status {cls}">{lbl}</span></td><td>{link}</td></tr>'

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Neferax Chain Report - {chain_name}</title>
<style>{CSS}</style></head><body>
<h1>⚡ Neferax — Attack Chain Report</h1>
<div class="meta">
<dt>Chain</dt><dd><strong>{chain_name.upper()}</strong></dd>
<dt>Target</dt><dd>{target}</dd>
<dt>Time</dt><dd class="info">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</dd>
<dt>Total Duration</dt><dd class="info">{total_ms:.0f}ms</dd>
</div>
<div class="summary">
<div><div class="num" style="color:#c9d1d9">{total}</div><div class="info">Tools</div></div>
<div><div class="num" style="color:#3fb950">{passed}</div><div class="info">Passed</div></div>
<div><div class="num" style="color:#f85149">{failed}</div><div class="info">Failed</div></div>
<div><div class="num" style="color:#d29922">{timedout}</div><div class="info">Timeout</div></div>
</div>
<table><tr><th>Tool</th><th>Duration</th><th>Status</th><th>Report</th></tr>
{rows}
</table>
<hr><p class="info">Generated by Neferax v2.0.0 — mastergeeky1-cloud/neferax</p>
</body></html>"""

    fpath.write_text(html)
    return fpath

def report_index():
    ensure_dir()
    reports = sorted(REPORTS_DIR.glob("*.html"), key=lambda p: p.stat().st_mtime, reverse=True)
    rows = ""
    for r in reports[:50]:
        size = len(r.read_text())
        rows += f'<tr><td><a href="{r.name}">{r.name}</a></td><td class="info">{size:,} bytes</td></tr>'

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Neferax Report Index</title>
<style>{CSS}</style></head><body>
<h1>⚡ Neferax — Report Index</h1>
<p class="info">{len(reports)} reports in {REPORTS_DIR}</p>
<table><tr><th>Report</th><th>Size</th></tr>
{rows}
</table>
<hr><p class="info">Generated by Neferax v2.0.0</p>
</body></html>"""
    idx = REPORTS_DIR / "index.html"
    idx.write_text(html)
    return idx
